/**
 * ShopEase - Product Catalog Data
 * In a real-world app this would come from an API; kept as a static
 * array here so the project runs standalone with no backend dependency.
 */

const PRODUCTS = [
  {
    id: 1,
    title: "Wireless Headphones",
    category: "Electronics",
    price: 2499,
    rating: 4.5,
    image: "https://picsum.photos/seed/headphones/400/300",
    description: "Over-ear wireless headphones with noise cancellation and 30-hour battery life.",
  },
  {
    id: 2,
    title: "Smart Watch",
    category: "Electronics",
    price: 3999,
    rating: 4.2,
    image: "https://picsum.photos/seed/smartwatch/400/300",
    description: "Fitness tracking smartwatch with heart-rate monitor and sleep tracking.",
  },
  {
    id: 3,
    title: "Running Shoes",
    category: "Fashion",
    price: 1899,
    rating: 4.6,
    image: "https://picsum.photos/seed/shoes/400/300",
    description: "Lightweight running shoes with breathable mesh and cushioned sole.",
  },
  {
    id: 4,
    title: "Backpack",
    category: "Fashion",
    price: 1299,
    rating: 4.3,
    image: "https://picsum.photos/seed/backpack/400/300",
    description: "Water-resistant 25L backpack with padded laptop compartment.",
  },
  {
    id: 5,
    title: "Coffee Maker",
    category: "Home",
    price: 2999,
    rating: 4.1,
    image: "https://picsum.photos/seed/coffeemaker/400/300",
    description: "Programmable drip coffee maker with 12-cup glass carafe.",
  },
  {
    id: 6,
    title: "Desk Lamp",
    category: "Home",
    price: 899,
    rating: 4.4,
    image: "https://picsum.photos/seed/desklamp/400/300",
    description: "Adjustable LED desk lamp with 3 brightness levels and USB charging port.",
  },
  {
    id: 7,
    title: "Yoga Mat",
    category: "Sports",
    price: 699,
    rating: 4.7,
    image: "https://picsum.photos/seed/yogamat/400/300",
    description: "Non-slip extra-thick yoga mat with carrying strap.",
  },
  {
    id: 8,
    title: "Dumbbell Set",
    category: "Sports",
    price: 2199,
    rating: 4.5,
    image: "https://picsum.photos/seed/dumbbell/400/300",
    description: "Adjustable dumbbell set, 2.5kg to 10kg per hand, with storage tray.",
  },
  {
    id: 9,
    title: "Bluetooth Speaker",
    category: "Electronics",
    price: 1599,
    rating: 4.3,
    image: "https://picsum.photos/seed/speaker/400/300",
    description: "Portable waterproof Bluetooth speaker with 12-hour playtime.",
  },
  {
    id: 10,
    title: "Sunglasses",
    category: "Fashion",
    price: 999,
    rating: 4.0,
    image: "https://picsum.photos/seed/sunglasses/400/300",
    description: "Polarized UV-protection sunglasses with lightweight metal frame.",
  },
  {
    id: 11,
    title: "Blender",
    category: "Home",
    price: 1799,
    rating: 4.2,
    image: "https://picsum.photos/seed/blender/400/300",
    description: "750W countertop blender with 3 speed settings and pulse mode.",
  },
  {
    id: 12,
    title: "Resistance Bands",
    category: "Sports",
    price: 499,
    rating: 4.6,
    image: "https://picsum.photos/seed/bands/400/300",
    description: "Set of 5 resistance bands with varying tension levels for home workouts.",
  },
];
